Repository team-popo/POPO-iOS, pull requests merged in 2021-10, with the labels that each got.

#42 [#22] NavigationController Extension 생성
  popo/popo/Sources/Extension/UINavigationController+Extension.swift
  popo/popo/Sources/ViewController/Login/LoginMethodViewController.swift
  popo/popo/Sources/ViewController/Onboarding/ConceptSelectViewController.swift
Labels: feat, cho2

#46 [#45] initializer 메서드 prefix 'init' 으로 변경, cell 클래스명, cell 변수명 변경
  popo/popo.xcodeproj/project.pbxproj
  popo/popo/Resources/Constant/Xib.swift
  popo/popo/Sources/Cell/Onboarding/ConceptSelectCollectionViewCell.swift
  popo/popo/Sources/Cell/Onboarding/ConceptSelectCollectionViewCell.xib
  popo/popo/Sources/Cell/Onboarding/OnboardingCollectionViewCell.swift
  popo/popo/Sources/Cell/Onboarding/OnboardingCollectionViewCell.xib
  popo/popo/Sources/Cell/PopoConcept/CategoryCollectionViewCell.swift
  popo/popo/Sources/Cell/PopoConcept/CategoryCollectionViewCell.xib
  popo/popo/Sources/ViewController/Onboarding/ConceptSelectViewController.swift
  popo/popo/Sources/ViewController/Onboarding/CoverColorViewController.swift
  popo/popo/Sources/ViewController/Onboarding/CoverGradientViewController.swift
  popo/popo/Sources/ViewController/Onboarding/OnboardingViewController.swift
  popo/popo/Sources/ViewController/PopoConcept/CategoryViewController.swift
Labels: hyun9, style

#47 [#43] 캘린더 뷰
  popo/Podfile
  popo/Podfile.lock
  popo/popo.xcodeproj/project.pbxproj
  popo/popo/Resources/Colors.xcassets/emptyCalendarBg.colorset/Contents.json
  popo/popo/Resources/Constant/Storyboard.swift
  popo/popo/Resources/Constant/ViewController.swift
  popo/popo/Resources/Constant/Xib.swift
  popo/popo/Resources/Storyboard/Calendar/Calendar.storyboard
  popo/popo/Sources/APIModel/Calendar/Calendar.swift
  popo/popo/Sources/APIModel/Calendar/Tracker.swift
  popo/popo/Sources/AppModel/AppMonth.swift
  popo/popo/Sources/Cell/Calendar/CalendarCollectionViewCell.swift
  popo/popo/Sources/Cell/Calendar/CalendarCollectionViewCell.xib
  popo/popo/Sources/Extension/UIColor+Extension.swift
  popo/popo/Sources/ViewController/Calendar/CalendarViewController.swift
  popo/popo/Sources/ViewController/Onboarding/CoverUserPhotoViewController.swift
Labels: feat, cho2

#54 [#53] 전봤캘 이미지 재등록시 index out of range 문제
  popo/popo/Sources/ViewController/Onboarding/CoverCalendarViewController.swift
  popo/popo/Sources/ViewController/PopoConcept/ConceptViewController.swift
Labels: fix, cho2

#56 [#55] Category 뷰와 Options 뷰 연결 및 네비게이션바 연결
  popo/popo.xcodeproj/project.pbxproj
  popo/popo/Resources/Storyboard/PopoConcept/Concept.storyboard
  popo/popo/Resources/Storyboard/PopoConcept/Options.storyboard
  popo/popo/Sources/SceneDelegate.swift
  popo/popo/Sources/ViewController/Calendar/CalendarViewController.swift
  popo/popo/Sources/ViewController/Onboarding/OnboardingViewController.swift
  popo/popo/Sources/ViewController/PopoConcept/CategoryViewController.swift
  popo/popo/Sources/ViewController/PopoConcept/ConceptViewController.swift
  popo/popo/Sources/ViewController/PopoConcept/OptionsViewController.swift
Labels: hyun9, feat

#64 [#63] PopoToday 뷰
  popo/popo.xcodeproj/project.pbxproj
  popo/popo/Resources/Constant/Storyboard.swift
  popo/popo/Resources/Constant/ViewController.swift
  popo/popo/Resources/Constant/Xib.swift
  popo/popo/Resources/Storyboard/PopoToday/PopoToday.storyboard
  popo/popo/Sources/Cell/PopoToday/OptionCollectionViewCell.swift
  popo/popo/Sources/Cell/PopoToday/OptionCollectionViewCell.xib
  popo/popo/Sources/Cell/PopoToday/TodayImageCollectionViewCell.swift
  popo/popo/Sources/Cell/PopoToday/TodayImageCollectionViewCell.xib
  popo/popo/Sources/SceneDelegate.swift
  popo/popo/Sources/ViewController/PopoToday/PopoTodayViewController.swift
Labels: feat, cho2

#67 [#62] Concept 뷰, Options 뷰 서버통신 및 분기처리, CustomOptions 뷰 버튼 활성화 및 데이터 전달
  popo/popo.xcodeproj/project.pbxproj
  popo/popo/Resources/Constant/Notification.swift
  popo/popo/Resources/Storyboard/PopoConcept/CustomOptions.storyboard
  popo/popo/Sources/APIModel/PopoConcept/Concept.swift
  popo/popo/Sources/APIServices/PopoAPI/PopoAPI.swift
  popo/popo/Sources/APIServices/PopoAPI/PopoService.swift
  popo/popo/Sources/AppModel/Options/OptionsList.swift
  popo/popo/Sources/Cell/PopoConcept/ConceptCollectionViewCell.xib
  popo/popo/Sources/View/OptionView.swift
  popo/popo/Sources/View/PlusOptionView.swift
  popo/popo/Sources/ViewController/Onboarding/CoverCalendarViewController.swift
  popo/popo/Sources/ViewController/PopoConcept/CategoryViewController.swift
  popo/popo/Sources/ViewController/PopoConcept/ConceptViewController.swift
  popo/popo/Sources/ViewController/PopoConcept/CustomOptionsViewController.swift
  popo/popo/Sources/ViewController/PopoConcept/OptionsViewController.swift
Labels: feat
